### ISSUE TITLE
Failed to download module for VMware vSphere

### ISSUE THREAD

**Issue by nagomikslai** [Terraform-VMWare-Modules/terraform-vsphere-vm#106]
Hi,
I failed with error of "failed to download module" when running terraform init. 

module "vm" {
  source = "Terraform-VMWare-Modules/vm/vsphere"
  version = "3.3.0"
  vmtemp = "Centos7.9"

Hope to get some helps from here.

Thank you. 

![terraform-init-output](https://user-images.githubusercontent.com/43594906/129695779-96e67f24-0881-41af-81f2-f3de90afc9c8.png)

**Comment by Arman-Keyoumarsi** [comment]
Hello, 

I just check on my machine and it seems working. 

![image](https://user-images.githubusercontent.com/5520007/129696805-9b8e9409-4115-4c44-ab10-3457e2b9e91b.jpeg)

Are you sure you have git installed and there are no firewall issue ?

**Comment by nagomikslai** [comment]
Hi,
Yes you are right. Firewall ruling issue. Got it fixed.
Thanks for your quick reply.
