### ISSUE TITLE
Add ability to start numbering at a particular value via "vmnameformat "

### ISSUE THREAD

**Issue by bfvogel** [Terraform-VMWare-Modules/terraform-vsphere-vm#109]
I've run into a client that has a naming convention of "${var.site}-${var.app}##"

I don't seem to see a way to provision multiple machine of differing types / configs and stick to this convention outside of staticvmname (which will significantly reduce ease of scale).  If one could start the numbering of a group one instances at "01" and group two instances at say "10" that would be great.  Noting of course that group one would never be able to scale past 9 instances without having to rebuild group two.

**Comment by Arman-Keyoumarsi** [comment]
Hi, 

Please refer  [here](https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm/issues/97), might help answer you question.

**Comment by bfvogel** [comment]
Fairly helpful.  Utilizing for_each and staticvmname I could accomplish a streamlined version of what I was thinking in OP.  However I still don't see a feesiblte way to scale role1 configs when only the hostname / IP changes from 2 to say 8 instances without having a blob of config per instance.  

My main goal here is to be able to scale horizontally within a role type without much configuration change.  I would like the instance numeric to just be a variable.  and then naming to be dynamic there in.  I've manage to accomplish this with the solution from my second post.  However, I expect that there will be limitations longterm due to the 9 role hard limit (roles are defined by a unit of 10) and a max of 9 instances per role (as 0 suffixed instances are nullified).

**Comment by johnypony3** [comment]
@bfvogel i added a comment to the link referenced by @Arman-Keyoumarsi 

[another method of achieving this, without for-each, also this is using template_cloudinit_config:](https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm/issues/97#issuecomment-908494336)
