### ISSUE TITLE
State of this repository

### ISSUE THREAD

**Issue by Satak** [Terraform-VMWare-Modules/terraform-vsphere-vm#11]
Hey,

is this repository maintained anymore? @Arman-Keyoumarsi seems to be the only official contributor. If there is only one contributor it leads to situation like this where issues are not tracked, response times are months long and PRs are not getting merged.

I would suggest that the original developer would allow more people into this repository as contributors if we want to have this as an official community Terraform module for VMware, VMware doesn't have their own official module unfortunately.

**Comment by Arman-Keyoumarsi** [comment]
Hey Sami, 

Sorry for the late reply and PR acceptance. I was off for a while and couldn't check my github messages!!

**Comment by Satak** [comment]
> Hey Sami,
> 
> Sorry for the late reply and PR acceptance. I was off for a while and couldn't check my github messages!!

OK totally understandable and good that you are back and the project is alive. If you accept other people to be contributors in this organization I'm happy to help what I can for now. We have quite huge investment for VMware Terraform so I think I could be a help for this. I have also started to investigate vcsim and other development tools for VMware/Terraform.

**Comment by Arman-Keyoumarsi** [comment]
Hey Sami, 

More than happy to have some help. My goal is also to have this org and repo well maintained and keep it updated with all the TF changes going forward.
