### ISSUE TITLE
Template location in different datacenter

### ISSUE THREAD

**Issue by tduvally** [Terraform-VMWare-Modules/terraform-vsphere-vm#13]
Ability to specify location of template.

I can't seem to find a way to specify a template that might me in a different dc. This code assumes it will be in the same dc as the vm being provisioned.

**Comment by tduvally** [comment]
I took a shot at a way to specify the location of the template's DC. This may be an edge case. 

[terraform-vsphere-vm-diff.txt](https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm/files/4417424/terraform-vsphere-vm-diff.txt)

**Comment by Arman-Keyoumarsi** [comment]
I will take a look but adding separate DC will create complexity and extra variables to the module. 

Have you tried sharing the template through vSphere Template Gallery ?

Is the Storage Template is shared between DCs ?
