### ISSUE TITLE
VM deployment is successful, VM do not join to domain

### ISSUE THREAD

**Issue by mithileshsudame09** [Terraform-VMWare-Modules/terraform-vsphere-vm#14]
below is my terraform code, environment variable and values are created in TFE enterprise variable section.

module "vm-deployment-trn" {
  source  = "automate.lplservices.com/lplfinancial/vm-deployment-module/vsphere"
  version = "1.0.6"
  dc                     = "XXXX"
  vmrp                   = "XXXX
  ds_cluster             = "XXXX"
  vmtemp                 = "XXXX"
  instances              = 2
  cpu_number             = 2
  ram_size               = 4096
  cpu_hot_add_enabled    = "true"
  cpu_hot_remove_enabled = "true"
  memory_hot_add_enabled = "true"
  vmname                 = "TFE-VM-Test0098"
  network_cards          = ["XXXX"] #Assign multiple cards
  ipv4submask            = ["21"]
  ipv4 = { #assign IPs per card
    "XXXX" = ["XXXX","XXXX"] 
  }
  data_disk_size_gb = [80, 40] // Aditional Disk to be used
  vmdns             = ["XXXX","XXXX"]
  vmgateway         = "XXXX"
  enable_disk_uuid = "true"
  auto_logon       = "true"
  orgname          = "XXXX"
  join_domain          = "var.windomain"
  domain_admin_user     = "var.domain_admin_user"
  domain_admin_password = "var.domain_admin_password"
  local_adminpass      = "var.local_adminpass"
  is_windows_image = "true"
}

**Comment by Arman-Keyoumarsi** [comment]
what is the user format ? 

In my experience the Domain\username usually do not work. try using username@domain.com.

Also it is much faster and easier to join the machine to domain using other cmg tools like Ansible or Chef. slight change in your domain admin password or its hash in your code will redeploy the entire VM again.
