### ISSUE TITLE
Multiple Instances with Multiple IP Addresses and Automatic IP reservation

### ISSUE THREAD

**Issue by blurtonator** [Terraform-VMWare-Modules/terraform-vsphere-vm#15]
Hello,
I am using your module to create virtual machines, and i have run across an issue. How does the ipv4 argument work when you have multiple instances? I have something like the following:

```
data "phpipam_first_free_address" "backup_address" { 
  count     = "${var.backup_cidr != "" ? : var.node_count : 0 }"
  subnet_id = data.phpipam_subnet.backup_subnet.subnet_id       
}

data "phpipam_first_free_address" "service_address" {   
  count     = "${var.service_cidr != "" ? : var.nod_count : 0 }" 
  subnet_id = data.phpipam_subnet.service_subnet.subnet_id
}
```

If count is > 1 in either scenario, I end up with a list. My question is, how would I express this in a form suitable for this module? I will have multiple NICs in multiple machines on different subnets (though, realistically, only two maximum per machine).

**Comment by Arman-Keyoumarsi** [comment]
Hello, 

Not sure if I am understanding your problem as the code you have paste here is unfamiliar to me but if you want to assign multiple NICs with different VLANs assign to each you can use the following 

`
network_cards          = ["VLAN01", "VLAN02"] #Assign multiple cards
  ipv4submask            = ["24", "8"]
  ipv4 = { #assign IPs per card
    "VLAN01" = ["192.168.0.4", "192.168.0.4"] // add more IPs for more instances!!
    "VLAN02"       = ["192.168.1.4", "192.168.153"]
  }
`

**Comment by SamyCoenen** [comment]
@blurtonator 
The module expects a ipv4 dict with a list of addresses in the values, seems like this is a Terraform data input sources question, not really within the scope of what a module needs to document as an example? Splat expressions might be interesting https://www.terraform.io/docs/configuration/expressions.html#splat-expressions
Can't you do something like this?
```hcl
network_cards          = ["VLAN01", "VLAN02"]
ipv4 = {
  "VLAN01" = "${data.phpipam_first_free_address.service_address.*.ip_address}"
  "VLAN02" = "${data.phpipam_first_free_address.backup_address.*.ip_address}"
}
```
