### ISSUE TITLE
Terraform Registry still on v3.5

### ISSUE THREAD

**Issue by damnsam** [Terraform-VMWare-Modules/terraform-vsphere-vm#153]
Not a code issue per se, just noticed the latest tagged version in the Terraform Registry for this module is 3.5, not 3.7

https://registry.terraform.io/modules/Terraform-VMWare-Modules/vm/vsphere/latest

**Comment by Arman-Keyoumarsi** [comment]
Good catch, It is fixed.

Thanks!
