### ISSUE TITLE
interfaces in map var.network 

### ISSUE THREAD

**Issue by voileux** [Terraform-VMWare-Modules/terraform-vsphere-vm#155]
The network variable is a map, while the order of the interfaces is important. Why isn't this variable a list of maps, to order the interface ?

**Comment by rachid2222** [comment]
to ensure that I have the correct order of the network interfaces, I added an identifier before the interface name.
for this I modified the following line main.tf

data "vsphere_network" "network" {
  count         = length(var.network)
  #name          = keys(var.network)[count.index]
  **name          = substr(keys(var.network)[count.index], 2, -1)**
  datacenter_id = data.vsphere_datacenter.dc.id
}

**Comment by damnsam** [comment]
I think this would break existing inventory files (trimming the first couple characters), but I can see why it is desirable in certain use cases, It appears that the nics are created alphabetically, hence the prefix "1:" and "2:" works.  Perhaps a n altered solution would be to include logic "if a colon is detected, remove the prefix", that way the enumeration works the same (new and old) preserving existing functionality? only issue, is the colon an allowed character in a network name?

**Comment by rachid2222** [comment]
that is indeed the case, just update only this line
**name = substr(keys(var.network)[count.index], 2, -1)** in data "vsphere_network" "network"

**Comment by damnsam** [comment]
I have some Oracle RAC systems to build in VMware, so this actually was one of the things that impacted me :) I created a branch on my fork repo which addresses two thing:

1.  Add three properties to data_disk (`disk_sharing`, `attach`, and `path`) - to create shared disks (not related)
2.  Added `network-delimiter` variable and code update similar to above's solution

For the second item, I decided on allowing the ability to use a "prefix" by identifying the delimiter.  For the use-case similar to the one mentioned by rachid2222, just set the value of` network-delimiter` to ":" and use "1:ProdNet" and "2:BackupNet" for the portgroup names.  The reason I went this route is that ":" is a valid character in a portgroup name, so this method allows one to use a different UNUSED character like ";", "|" or "~"

Have a look at the diff [here](https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm/compare/master...damnsam:terraform-vsphere-vm:network-and-disk-updates), give it a try, and I'll create a pull request if all good

**Comment by rachid2222** [comment]
good, it's ok for me :), thank's @damnsam 
network-delimiter to ":"  => **network_delimiter to ":"**

before pull request can you add some lines below, I used it to update lifecycle by script dynamically

resource "vsphere_virtual_machine" "vm" {
...
  **# https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#extra_config_reboot_required
  extra_config_reboot_required = true

  # https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle
  lifecycle {
    create_before_destroy = false
    prevent_destroy = false
    #ignore_changes
  }**
}

**Comment by damnsam** [comment]
I think lifecycle is a bit of a wonky subject, I have yet to get that to work dynamically, how do you do it? Maybe we should address that seperately.

**Comment by rachid2222** [comment]
OK to separate the two subjects

**Comment by damnsam** [comment]
This issue should be addressed now in the latest code update, I think @Arman-Keyoumarsi can now close the issue
