### ISSUE TITLE
Different datastores per data disk

### ISSUE THREAD

**Issue by SamyCoenen** [Terraform-VMWare-Modules/terraform-vsphere-vm#16]
Additional disks can be defined using this array
```hcl
data_disk_size_gb = [10, 5]
```
But it's not possible yet to define the datastore where you want to store these disks.

For example with:

```hcl
data_disk_datastore = ["vsanDatastore"]
```

There are other attributes for disks that would also be useful, for example configurable unit numbers so you can choose the scsi_controller, but before adding a pull-request myself I would like to know if this is something you would be willing to merge? @Arman-Keyoumarsi

**Comment by Arman-Keyoumarsi** [comment]
Hey Sammy,

For sure, just use an if switch so the variable wouldn't be mandatory and
assign null to it in the resource itself.

Regards,
AK
