### ISSUE TITLE
New Data Disk settings break Data store cluster use case

### ISSUE THREAD

**Issue by wkleinhenz** [Terraform-VMWare-Modules/terraform-vsphere-vm#18]
Looks like the changes made in 1.0.3 break the ability to only specify  a data store cluster, in my env I dont need to specify data stores individually but when running the apply with only `ds_cluster="DatastoreCluster"` and specifying thin provisioning fails with the following error 
![image](https://user-images.githubusercontent.com/18507996/81635624-a0069f00-93df-11ea-97aa-5ead46a9b722.png)
 then if i use the data store cluster as input there I get 
![image](https://user-images.githubusercontent.com/18507996/81635660-b4e33280-93df-11ea-98a1-4aa20ec050eb.png)

so i looks like either something needs to be done to allow ds_cluster to be able to be specified on its own or allow the new bits to accept ds cluster as valid inputs

**Comment by Arman-Keyoumarsi** [comment]
Hello,

You are right, I have tried to fix the issue to some extent but I don't see where the disk_datastore is actually used in VM resource creation. 

I have created a new branch  feature/disk-datastore with the partial fix which won't give you error anymore but couldn't really test the data disk store as i don't have template ready for it.

In this branch if you define disk_datastore and data_disk_datastore you still get the following error where I suspect coming from my VM template but not sure.

![image](https://user-images.githubusercontent.com/5520007/81800010-74d09c80-9512-11ea-85b0-25d5019ab315.png)

As a result I have rolled back the release and revert the commit until we can fix this issue completely.

**Comment by SamyCoenen** [comment]
This was my fault
https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm/blob/f7bfa00f39f13dae1d975e3e2657686ea42764a6/variables.tf#L160
should have been an empty string instead of null
```hcl
default = ""
```

**Comment by wkleinhenz** [comment]
Thanks for the quick response ill pull the new version later today and close if it works

**Comment by wkleinhenz** [comment]
looks like the code in master seems to work as intended
