### ISSUE TITLE
Error: Invalid index when add only one network card

### ISSUE THREAD

**Issue by Piyaphong** [Terraform-VMWare-Modules/terraform-vsphere-vm#21]
I 'm newbie in terraform. now I try to use this module and got some error 

rror: Invalid index

  on .terraform/modules/my_vsphere/terraform-vsphere-vm-1.0.2/main.tf line 129, in resource "vsphere_virtual_machine" "Linux":
 129:           ipv4_address = var.ipv4[var.network_cards[network_interface.key]][count.index]
    |----------------
    | count.index is 1
    | network_interface.key is 0
    | var.ipv4 is map of tuple with 1 element
    | var.network_cards is list of string with 1 element

The given key does not identify an element in this collection value.

here is my tf config
network_cards          = ["VLAN132"]
  ipv4submask            = ["24"]
  ipv4 = {
    "VLAN132" = ["192.168.132.213"] // Here the first instance will use Static Ip and Second set to DHCP
  }
  data_disk_size_gb = [10, 5] // Aditional Disk to be used
  thin_provisioned  = ["true", "true"]
  vmdns             = ["192.168.131.10", "8.8.8.8"]
  vmgateway         = "192.168.132.254"

please help.

**Comment by Arman-Keyoumarsi** [comment]
Hey, 

I can't reproduce the issue in my environment. It works fine with one network card. can you remove sensitive info and post your complete config and the error ?

Is the VLAN you have defined exist in your vCenter ?

**Comment by Piyaphong** [comment]
#main.tf
provider "vsphere" {
  version   = "1.11.0"
  vsphere_server  = "${var.vsphere_vcenter}"
  user      = "${var.vsphere_user}"
  password  = "${var.vsphere_password}"
  allow_unverified_ssl  = "${var.vsphere_unverified_ssl}"
}

#module.tf
module "my_vsphere" {
  source                 = "Terraform-VMWare-Modules/vm/vsphere"
  version                = "1.0.2"
  dc                     = "MYDATACENTER2"
  vmrp                   = "MYCLUSTER2/Resources"
  vmfolder               = "iac"
  datastore              = "Datastore04"
  vmtemp                 = "terraform-template/ubuntu-16.04-terraform-template"
  instances              = 2
  cpu_number             = 2
  ram_size               = 2096
  cpu_hot_add_enabled    = "true"
  cpu_hot_remove_enabled = "true"
  memory_hot_add_enabled = "true"
  vmname                 = "test-iac"
  vmdomain               = "mydomain.lab"
  network_cards          = ["VLAN132"]
  ipv4submask            = ["24"]
  ipv4 = {
    "VLAN132" = ["192.168.132.213"] // Here the first instance will use Static Ip and Second set to DHCP
  }
  data_disk_size_gb = [10, 5] // Aditional Disk to be used
  thin_provisioned  = ["true", "true"]
  vmdns             = ["192.168.131.10", "8.8.8.8"]
  vmgateway         = "192.168.132.254"
}

I was defined VLAN132 on vcenter.

**Comment by SamyCoenen** [comment]
@Piyaphong You have  `instances = 2` but you don't define multiple addresses in ipv4, ipv4submask?

**Comment by Piyaphong** [comment]
> @Piyaphong You have `instances = 2` but you don't define multiple addresses in ipv4, ipv4submask?

Oh! I see. Thank you very much.
