### ISSUE TITLE
Module depends_on

### ISSUE THREAD

**Issue by keachi** [Terraform-VMWare-Modules/terraform-vsphere-vm#27]
## Summary
A way to set a module depends on would be nice. I had the issue that when I'm dynamically generating networks on NSX-t and attaching virtual machines to those networks the module fails as the network isn't already defined.

## Error
```
Error: error fetching network: network 'net_example' not found on .terraform/modules/terraform-vsphere-vm/main.tf line 34, in data "vsphere_network" "network":
  34: data "vsphere_network" "network" {
```

## Workaround
As Terraform doesn't have a `depends_on` for modules, I implemented that like described in [this discussion](https://discuss.hashicorp.com/t/tips-howto-implement-module-depends-on-emulation/2305). This works for me, but in general it should also allow to set no dependencies.

**Comment by Arman-Keyoumarsi** [comment]
good point, I have added the depend on and works as expected. 

Only downside is that it only work with external modules. would have been nice if we could pass null_Resource as depend on. 

I will publish a new version soon.
