### ISSUE TITLE
Add CDROM Options

### ISSUE THREAD

**Issue by rick-clemens** [Terraform-VMWare-Modules/terraform-vsphere-vm#31]
Can CDROM Options be added to this module so that a CDROM can be added to a VM as part of the build procedure?

**Comment by Arman-Keyoumarsi** [comment]
Will Look into it!!

**Comment by Arman-Keyoumarsi** [comment]
I don't think it is possible to do that. CDROM option do not accept null value, therefore I can not include it in the module without forcing it for every build. You can have the CDROM define in your template if you need to use one or build your entire image using Packer and then deploy using Terraform

```hcl
cdrom {                                                                                                                                            
      datastore_id = null                                                                                                                              
      path         = ""                                                                                                                                
  } 

Error: cdrom.0: Either client_device or datastore_id and path must be set

  on terraform-vsphere-vm/main.tf line 64, in resource "vsphere_virtual_machine" "Linux":
  64: resource "vsphere_virtual_machine" "Linux" {
```

**Comment by bradlylong** [comment]
Can this be revisited? I feel like you are choosing not to expose a key piece of functionality of the underlying resource. I see people forking this project just to add that change, and I'm about to have to do the same.
