### ISSUE TITLE
How to attach backup partition to one node in instance set?

### ISSUE THREAD

**Issue by warmfusion** [Terraform-VMWare-Modules/terraform-vsphere-vm#33]
Hi,

We're trying to setup a small cluster of database nodes, and would like one of those nodes to have an additional disk attached for backup purposes. We're currently using two blocks of configuration, but this results in inconsistent naming and opens ourselves up to inconsistent deployments.

Do you have any advice?

The following shows a template for the cluster, and I"d like to be able to take the first node and give it an additional disk during TF Apply.

```terraform
module "my-db-prod-v1" {
	source  = "Terraform-VMWare-Modules/vm/vsphere"
	version = "1.3.0"
	vmtemp = "debian-9-12"
	instances = 3
	vmname = "my-db-prod-v1-"
	vmrp = "db-prod"
	cpu_hot_add_enabled = "true"
	cpu_hot_remove_enabled = "false"
	cpu_number = "8"
	memory_hot_add_enabled = "true"
	ram_size = "16384"
	wait_for_guest_net_routable = "false"
	data_disk_size_gb = [500]
	dc = "uk-lon-pub"
	datastore = "ssd-local"
	network_cards = ["DATA-STORE"]
	tags = {
		"guest.product"		= "example"
		"guest.service"		= "mysql"
	}
	ipv4 = {
		"DATA-STORE" = ["172.20.10.36"]
	}
	ipv4submask = ["24"]
	vmdns = ["185.0.0.1", "185.0.0.2"]
	vmgateway = "172.20.10.1"
	vmdomain = "uk-lon.data-store.example.com"
	dns_suffix_list = [ "uk-lon.data-store.example.com", "example.com"]
}
```

Thanks

**Comment by Arman-Keyoumarsi** [comment]
Hi, I am afraid that is not possible. but you use literalname variable for your second block to make your naming consistent.

hope that helps.
