### ISSUE TITLE
Query - How to attach additional disk to one node in cluster?

### ISSUE THREAD

**Issue by warmfusion** [Terraform-VMWare-Modules/terraform-vsphere-vm#38]
Howdy,

We're using your module to configure clusters of hosts for various things, but one use case we've not figured out yet is how to attach a disk to one node out of a cluster.

Specifically, when setting up MySQL Percona clusters, we typically give one node an additional disk mount for purposes of backing up the data. Problem is, we don't know how to do this without having two chunks of configuration resulting in some pretty ugly deployments.

Any help would be really appreciated

Toby

**Comment by Arman-Keyoumarsi** [comment]
Hi, 

This is not possible for a Terraform Module. The whole concept of TF Modules are reusable infrastructure blueprints that are equal repeatable.

The best way is to use the same module for the server with extra disk like as you mentioned. the code is in same workspace it should be a problem. The other way cloud have been using the [vsphere_virtual_disk](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_disk), but we still need to attach it within the module.
