### ISSUE TITLE
how to use file provisioner within vm resource block to work with all instances of vms

### ISSUE THREAD

**Issue by kchoudhury** [Terraform-VMWare-Modules/terraform-vsphere-vm#4]
I am trying to add the file provisioner within this module but dont know how this will work for all the instances created depending on variable instances , the below code gives cycle error . I basically need to copy this folder on all the vms created . 

provisioner "file" {
  source      = "copy-test/"
  destination = "C:/automation"

  connection {
    type     = "winrm"
    host = vsphere_virtual_machine.Windows[count.index].default_ip_address
    user     = var.domain_admin_user
    password = var.domain_admin_password
    }

  }

**Comment by piwi3910** [comment]
same request here:
the module works perfect. but i can't see how the resources would be called to use a provisioner with.
module.example-server-linuxvm-withdatadisk.vsphere_virtual_machine.Linux[0]

when using this name, it says . is not allowed in a resource name.
and can't find anything else that looks like a resource name.

**Comment by Arman-Keyoumarsi** [comment]
You can retrive the IPs and VM Names using the module out put.

Lets say you local module name is WindowsVM then you can get the ip using the following

"${module.WindowsVM.Windows-ip[0]}"

**Comment by kchoudhury** [comment]
Thanks , i also found another way which works if you place the file provisioner within the virtual machine resource in the module codebase main.tf . Here we can use the self keyword , see example below . By doing this the below provisioner works for all the instances of vm resources that get created

provisioner "file" {
  source      = "copy-test/"
  destination = "C:/automation"

  connection {
    type     = "winrm"
    host     = self.default_ip_address
    user     = var.domain_admin_user
    password = var.domain_admin_password
    }
  }
