### ISSUE TITLE
cannot traverse type VmwareDistributedVirtualSwitch

### ISSUE THREAD

**Issue by skircr** [Terraform-VMWare-Modules/terraform-vsphere-vm#40]
Hi, we using a distributed switch with many VLANs.
When we provide network card name as ["DistributedSwitchName/DistributedPortGroupName"] we get following error:
"Error: error fetching network: cannot traverse type VmwareDistributedVirtualSwitch"

Can you please advise on how to properly use Distributed Port Group?

Thanks

**Comment by Arman-Keyoumarsi** [comment]
There is a similar case [here](https://github.com/hashicorp/terraform-provider-vsphere/issues/855) . Try using "%2f" instead of "/"
