### ISSUE TITLE
Use tags for depends_on

### ISSUE THREAD

**Issue by AxiansFrance** [Terraform-VMWare-Modules/terraform-vsphere-vm#47]
Hello ,
I'm currently trying to use a tag_depends_on. 

In the first place i create the tag and the category in the main.tf, then a tag_depends_on resources. 
But when i trigger the plan, an error saying that the cateogry is not found in the main.tf appears.
Knowing  that the resources that need the tag_depends_on are many modules that creates many vm.
Like so, whe can't make one module wait for the other.

If anyone could explain to me how to use tag_depends_on in this case, it would be appreciated.

**Comment by Arman-Keyoumarsi** [comment]
Its same as any depends_on where you can define the pre-required module. If you are on Terraform v 0.13 you can ignore this variable and use the depends on directly in your module configuration. [Reference](https://www.hashicorp.com/blog/terraform-0-13-brings-powerful-meta-arguments-to-modular-workflows)
