### ISSUE TITLE
Windows customization runonce does not seem to be working on my environment

### ISSUE THREAD

**Issue by kchoudhury** [Terraform-VMWare-Modules/terraform-vsphere-vm#5]
When using the template for a windows linked clone run once commands do not seem to be executing , i am setting the below parameters . The autologon does happen as expected but the directory does not get created

auto_logon  = "true"
  auto_logon_count = "1"
  run_once = ["mkdir c:\\admin", "echo runonce-test >> c:\\admin\\logs.txt"]

Tried on windows 10 and win server 2k19

**Comment by Arman-Keyoumarsi** [comment]
I need to check that!!

**Comment by Arman-Keyoumarsi** [comment]
> When using the template for a windows linked clone run once commands do not seem to be executing , i am setting the below parameters . The autologon does happen as expected but the directory does not get created
> 
> auto_logon = "true"
> auto_logon_count = "1"
> run_once = ["mkdir c:\admin", "echo runonce-test >> c:\admin\logs.txt"]
> 
> Tried on windows 10 and win server 2k19

Hey, I have tried the runonce and it works, you can try with something like 
run_once         = ["route add 10.116.0.0 mask 255.255.0.0 192.168.0.1 -p"]
Result
![image](https://user-images.githubusercontent.com/5520007/64955974-deb47b80-d889-11e9-80a4-ba1e7ca7de1a.png)

Regards,
