### ISSUE TITLE
make clone and customization optional

### ISSUE THREAD

**Issue by uutest74** [Terraform-VMWare-Modules/terraform-vsphere-vm#53]
Hi!
In some rare cases (customization not work for this OS, user need 2 install OS by himself, etc) not need customization or ever cloning from template. Can you make them optional with some parameters like no_os/no_cust?
For making some blocks optional in my old code i used constructions like code block below.
Also with this method you can avoid separating windows and linux vms on different resources using dynamic customize instead.... But it is not exactly))

dynamic clone {
  for_each = var.VMS[count.index].no_os == true ? [] : [1]
    content{
      template_uuid = data.vsphere_virtual_machine.templates.*.id[count.index]
      dynamic customize {
        for_each = replace(data.vsphere_virtual_machine.templates.*.guest_id[count.index], "/.*other.*/", "other") == "other" ? [] : [1]
        content {
          dynamic linux_options {
            for_each = replace(data.vsphere_virtual_machine.templates.*.guest_id[count.index], "/.*win.*/", "win") == "win" ? [] : [1]
            content {
              host_name = var.VMS[count.index].name
              domain    = var.vm_common_opts.dns_suffix_list[0]
              time_zone = var.vm_common_opts.time_zone_lx
            }
          }
          dynamic windows_options {
            for_each = replace(data.vsphere_virtual_machine.templates.*.guest_id[count.index], "/.*windows.*/", "windows") != "windows" ? [] : [1]
            content {
              computer_name = var.VMS[count.index].name
              time_zone     = var.vm_common_opts.time_zone_win
            }
          }

**Comment by Arman-Keyoumarsi** [comment]
Setting up OS after terraform deployment really defeat the whole purpose of immutable infrastructure. I suggest you to use Packer for managing your Templates and install OS  into the VMs.

**Comment by uutest74** [comment]
not surprised that your module has more forks than stars....

**Comment by Arman-Keyoumarsi** [comment]
> not surprised that your module has more forks than stars....

feel free to fork, or do a pull request for your suggestion. it’s an open source project after all.

**Comment by bobmihada** [comment]
Bro, you rock.  I appreciate you and this project.  This was so helpful.

**Comment by Rodri9o** [comment]
Exceptional work @Arman-Keyoumarsi - rock on \\m//.

**Comment by mazzy89** [comment]
I have an use case that motivate the optional clone block but still not defeating the purpouse of Terraforn as Arman says.

Often you want to manage VMWare machines and then bootstrap them with PXE. At that point the clone block here does bit make much sense.

What do you think?

**Comment by Arman-Keyoumarsi** [comment]
I am open to PR, but I see it super complicated to implement. since you don't need the Windows or Linux customization, I think it is better to create a new module that deploy VMs without templates. 

I am open to create a new repo in this org and collaborate on the module.

**Comment by mazzy89** [comment]
Yes. I agree with you. Introducing this change in here would make the module harder.

Yes please. Can you create a repo and I would be keen to collaborate
