### ISSUE TITLE
NVME Disks

### ISSUE THREAD

**Issue by hutger** [Terraform-VMWare-Modules/terraform-vsphere-vm#58]
Hi there, 

I've created a template using Packer with three attached NVME disks. When I try to run Terraform for deploying an instance using this template, I get the message: 

`Error: there must be at least one disk specified`

It seems that Terraform is not able to find the NVME disks attached (since the only opinions are pvscsi, buslogic, etc, but none NVME), even though I add an extra_config informing NVME is presenting:

```
disk_size_gb                    = var.vmRootDiskSize
scsi_type                       = var.vmScsiType
extra_config                    = {
    "nvme0.present"                 = "True"
    "nvme0.0.present"               = "True"
```

Have you come across this issue before? Any thoughts?

PS: If we deploy a new instance using the Template manually, the instance boots up as expected.

**Comment by Arman-Keyoumarsi** [comment]
Try omitting scsi_type in your code so the module takes the one from template itself.

` scsi_type              = var.scsi_type != "" ? var.scsi_type : data.vsphere_virtual_machine.template.scsi_type`

**Comment by hutger** [comment]
Hi @Arman-Keyoumarsi , thanks for your response. I tried before this option before but Terraform raised an error saying that `scsi_type` is a required input. Usually, scsi_type can be omitted,  since Terraform seems to recognize the type from the attached disk. However, since the disks are NVME, Terraform seems not to reckon the disks and, hence, asks for an explicit type declaration.
