### ISSUE TITLE
Clone - Not taking configrations from template - Windows

### ISSUE THREAD

**Issue by ashischangan** [Terraform-VMWare-Modules/terraform-vsphere-vm#59]
i am able to create vm from template but after creating VM it is not taking all configurations from template and need to reapply configuration again like timezone,windows os product key,cpu/ram. Is this expected behavior or need to make some changes to take all configuration from template?

**Comment by Arman-Keyoumarsi** [comment]
Hi,

Cpu and RAM are not taken from the template, you should define them if you don't want use the default variables. For the customization, do not sysprep your template. It will be done through the module itself.

Hope that helps!

**Comment by ashischangan** [comment]
Thanks @Arman-Keyoumarsi for the help. The problem i am having is that if i use module then it does not allow to use same oneproduct key to activate windows for multiple VM's. Due to this i need to use new product key for each new windows VM which is costly. The same we don't need to activate windows when we create VM from template in vpshere using **"Create new vm from template"** option since in base template windows is already activated.  Do have any suggestion or workaround for this scenario?

Thanks for the help.

**Comment by mazzy89** [comment]
I have an use case that motivate the optional clone block but still not defeating the purpouse of Terraforn as Arman says.

Often you want to manage VMWare machines and then bootstrap them with PXE. At that point the clone block here does bit make much sense.

What do you think?
