### ISSUE TITLE
ifcfg-ens192: DOMAIN="" and SEARCH="" values

### ISSUE THREAD

**Issue by Rodri9o** [Terraform-VMWare-Modules/terraform-vsphere-vm#62]
Say we have interface config  /etc/sysconfig/network-scripts/ifcfg-ens192

This code 

`var.vmdomain = "domain1.com"`
`dns_suffix_list = ["domain2.com"]`

Results in this wrong entry in the interface config file

`DOMAIN="domain2.com"`

when the correct entries  should be 

`DOMAIN="domain1.com"`
`SEARCH="domain2.com"`

**MY ENVIRONMENT**

DHCP
CentOS Linux release 7.8.2003 (Core)
Terraform v0.13.4
vSphere Version: 7.0.0  Build: 16189207

**Comment by Arman-Keyoumarsi** [comment]
There are three distinct variables for configuring DNS and Domain.

![image](https://user-images.githubusercontent.com/5520007/103334892-6a4c1e80-4a73-11eb-8f20-072c71b03536.png)

Global DNS settings
The following settings configure DNS globally, generally for Linux systems. For Windows systems, this is done per-interface, see network interface settings.

dns_server_list - The list of DNS servers to configure on a virtual machine.
dns_suffix_list - A list of DNS search domains to add to the DNS configuration on the virtual machine.

domain - (Required) The domain name for this machine. This, along with host_name, make up the FQDN of this virtual machine.

**Comment by Rodri9o** [comment]
Thanks for the clarification, Arman.

Having DOMAIN='domain.com'   or    SEARCH='domain.com'  in  /etc/sysconfig/network-scripts/ifcfg-ens192
results in the same outcome. A tad confusing at first.
