### ISSUE TITLE
set user and passwor value

### ISSUE THREAD

**Issue by eunicebello7** [Terraform-VMWare-Modules/terraform-vsphere-vm#7]
How or where do I set the user and password value? No matter what I do, I keep getting this error:

```
Error: Missing required argument
The argument "user" is required, but was not set.

Error: Missing required argument
The argument "password" is required, but was not set.
```

**Comment by Arman-Keyoumarsi** [comment]
Can you be more specific and provide an example ?

Usually you dont need need to specify the password for Linux deployment. It is only required for windows when joining the VM to the domain.

**Comment by jostmart** [comment]
If you copy paste one of the examples, say module "example-server-windowsvm-advanced" and run terraform plan, it returns the output eunicebello7 pasted.

The documentation or code does not show how to configure user or password.

**Comment by nerdeverde** [comment]
I believe the required user and password in this case is for the Vsphere provider. You would need to build a provider block for vsphere which includes these values. See the [VSphere Provider Docs](https://www.terraform.io/docs/providers/vsphere/index.html). Something like the following at the beginning of your .tf file that uses the module would provide the necessary setup. If you don't provide the variable values on the command line or in a .tfvars file, you get prompted for them when you run `terraform plan` or `terraform apply`.

```HCL
provider "vsphere" {
    user = "${var.vsphere_user}"
    password = "${var.vsphere_password}"
    vsphere_server = "${var.vsphere_server}"
    allow_unverified_ssl = true // Set as needed based on your VCenter server certificate
}

variable "vsphere_user" {
    type = string
}

variable "vsphere_password" {
    type = string
}

variable "vsphere_server" {
    type = string
}
```

**Comment by Satak** [comment]
Created a PR to clear some of the documentation: https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm/pull/10

I was thinking to also add the `provider` section to all examples. Should that be added to prevent this?

**Comment by Arman-Keyoumarsi** [comment]
Hey Sami,

I don't mind adding provider section to the example.
