### ISSUE TITLE
IP Address & Name output fails;  vsphere_virtual_machine.vm.*.name

### ISSUE THREAD

**Issue by Rodri9o** [Terraform-VMWare-Modules/terraform-vsphere-vm#94]
Ran this as described in the examples with the goal of outputting the IP address of each VM  (for Configuration Management purposes) but received the following: 

Plan output:
![image](https://user-images.githubusercontent.com/9559297/120874368-56519f00-c574-11eb-9151-1b5d47942edc.png)

output.tf
![image](https://user-images.githubusercontent.com/9559297/120874382-623d6100-c574-11eb-9106-0c72129e0b36.png)

env:
![image](https://user-images.githubusercontent.com/9559297/120874435-acbedd80-c574-11eb-901e-3dd56d80e10a.png)

**Comment by Arman-Keyoumarsi** [comment]
Are you using for each at the root module ?

If you are following examples from test section, I have updated the sanity test with the output variable [sanity](https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm/blob/master/tests/sanity/main.tfl)
```hcl
output "VM" {
  value = tomap({
    for k, i in module.example-server-basic : k => i.VM
  })
}
```
You need to use map for output if you have for each used when declaring your module.

**Comment by Rodri9o** [comment]
Thanks for the clarification.
