### ISSUE TITLE
Module not working properly with vSphere Customization using Cloud-Init

### ISSUE THREAD

**Issue by PSTobiasMueller** [Terraform-VMWare-Modules/terraform-vsphere-vm#97]
Hello,

i'm currently testing this module to use it as the default deployment for all of our Terraform generated VMs.

We've VM Templates, build by Packer, with the [VMware-GuestInfo](https://github.com/vmware/cloud-init-vmware-guestinfo) Addon included. Currently we deploy our VMs with a simple Terraform Module that allows us to specify some options and then the VM gets deployed with some extra_config
```
  extra_config = {
    "guestinfo.userdata"          = data.template_cloudinit_config.user_data.rendered
    "guestinfo.userdata.encoding" = "base64"
    "guestinfo.metdata"          = data.vm_metdata
    "guestinfo.metdata.encoding" = "base64"
  }
```

That works fine at the moment, but the module is far less flexible then your vsphere-vm modul. Thats why i tried to use your Module to deploy our VMs. But that wasn't really working. I couldn't really use the extra_config variable, because those variable would be used for all VMs and with the Cloud Init MetaData/Userdatd i needed the variable different for each vm.

With this in mind i thought i could leverage the customization process from vsphere that can now use cloud-init, too. But there seems to be the problem that we currently in this module dosn't specify some sort of UserData. The first boot is working well. The VMs get the correct network configuration and everything seems fine. But after a Restart Cloud-Init dosn't load the vsphere datasource and uses some default noCloud Configuration. I tried a lot but it seems like i can't change that behaviour. The only option would be to remove cloud-init after the deployment, but then i couldn't update the ip or other network related stuff when i change variables in my terraform deployment.

When i disable the vSphere Customization via cloud-init in the Packer Templates i can deploy the VMs without problem with the correct network configuration and also reboots are no problem. But thats a solution i'm not happy with. Since we have some Tools like Rancher, that use a nearly identical image with cloud-init i don't want 2 different configuration schemas, aka terraform uses the old perl vsphere customization and other tools use cloud-init for vm customization.

My consideration was to enhance your module with the ability to include a list of cloud-init configuration that would be passed to the extra_config block when cloning a vm. i thought about 3 variables:

```
variable "cloud_init_customization" {
  description = "Should the Module specifiy UserData and MetaData via extra_config"
  type        = bool
  default     = false
}
variable "cloud_init_user_data" {
  description = "UserData for each VM"
  type        = list(any)
  default     = null
}

variable "cloud_init_meta_data" {
  description = "MetaData for each VM"
  type        = list(any)
  default     = null
}
```

When those variables exists they would be added to the extra_config block when creating a linux vm. To prevent conflicts with existing deployment that may use this module and already specify `guestinfo.userdata` or `guestinfo.metadata` i would add an switch that the cloud_init function is only used when explicit requested via `cloud_init_customization`.

Would that be something that we could then merge into your module or do you mind another idea of implementing it?

Greetings
Tobias

**Comment by Arman-Keyoumarsi** [comment]
Hi Tobias, 

Interesting problem. If I understood it correct, you need different config to be applied for each vm within the module right ?

Referring to:
>  I couldn't really use the extra_config variable, because those variable would be used for all VMs and with the Cloud Init MetaData/Userdatd i needed the variable different for each vm.

But isn't this break the whole concept of Immutable infrastructure ? Currently we do not support any kind of different configuration within the module for that specific reason. The idea is when you define instance numbers within the module you know each VM has the exact same configuration. 

One solution to your problem would be using for_each variable when using the module itself this way you can keep your fixed variables constant and use both different names (if you wish to) and different configuration for the VMs. 

```hcl
Example of using for_Each
vm = {
  VM1 = {
    network = {
      "VM Port Group" = ["10.13.13.2", ""], # To use DHCP create Empty list for each instance
      "VM Port Group" = ["", ""]
    }
extra_config =  {
    "guestinfo.userdata"          = data.template_cloudinit_config.user_data.rendered
    "guestinfo.userdata.encoding" = "base64"
    "guestinfo.metdata"          = data.vm_metdata
    "guestinfo.metdata.encoding" = "base64"
  }
  },
  VM2 = {
    network = {
      "VM Port Group" = ["10.13.13.2", ""], # To use DHCP create Empty list for each instance
      "VM Port Group" = ["", ""]
    }
  extra_config =  {
    "guestinfo.userdata"          = data.template_cloudinit_config.user_data.rendered
    "guestinfo.userdata.encoding" = "base64"
    "guestinfo.metdata"          = data.vm_metdata
    "guestinfo.metdata.encoding" = "base64"
  }
  }
}
variable "vm" {
  type = map(object({
    network          = map(list(string))
    vmgateway        = string
    dns_servers      = list(string)
   extar_config = map(any)
  }))
}

module "example-server-basic" {
  source           = "../../"
  for_each         = var.vm
  vmtemp           = "fill"
    vmrp             = "fill" 
    dc               = "fill"
    vmfolder         = "fill"  
    datastore        = "fill"  
    dns_servers      = null
    vmgateway        = "10.13.13.1"
  network          = each.value.network
  instances      = 2
  vmnameformat   = "%03d${var.env}"
  vmname         = "terraform-sanitytest"
  extra_config = each.value.extra_config #This is when you define different config for each set of VMs
}
```
using the method above you get two benefits. First you can define set of VMs with equal config using the instant variable. Second you can avoid repeating the variables that are constant for your scenario.

Hope that helps and solve your problem.

By the way, I didn't quite get how you would pass the  cloud_init_customization to the extra config ? by merging the two list to a map ?

Regards, 
Arman

**Comment by PSTobiasMueller** [comment]
Hi Arman,
 
> > I couldn't really use the extra_config variable, because those variable would be used for all VMs and with the Cloud Init MetaData/Userdatd i needed the variable different for each vm.
> 
> But isn't this break the whole concept of Immutable infrastructure ? Currently we do not support any kind of different configuration within the module for that specific reason. The idea is when you define instance numbers within the module you know each VM has the exact same configuration.

Not really, since the Cloud Init Data is also created via terraform. We've a template that will deploy the machine and use terraform and cloud-init/user-data to create a special user, copy a ssh key and a password. The ssh-key and the passwort are auto-generated, stored in hashicop vault and unique for each machine.


> One solution to your problem would be using for_each variable when using the module itself this way you can keep your fixed variables constant and use both different names (if you wish to) and different configuration for the VMs.
>
> using the method above you get two benefits. First you can define set of VMs with equal config using the instant variable. Second you can avoid repeating the variables that are constant for your scenario.
>
> Hope that helps and solve your problem.

This could be a solutions. I hadn't thought about using the foreach function in custom modules. Thanks!

 
> By the way, I didn't quite get how you would pass the cloud_init_customization to the extra config ? by merging the two list to a map ?

Hmm. extra_config is already a map, my thought was to simple [merge](https://www.terraform.io/docs/language/functions/merge.html) it with a another map i created with the input from the cloud init variables.

 
Regards,
Tobias

**Comment by johnypony3** [comment]
another method of achieving this, without for-each, also this is using `template_cloudinit_config`:

> variables.tf
```terraform
variable "num_instances" {
  description = "number of instances you want deploy from the template."
  default     = 1
}
```

> locals.tf
```terraform
  userdata = [
    for n in range(var.num_instances) : templatefile("${path.module}/templates/userdata.yml", {
      hostname           =  "bingobongo${n}"
    })
  ]
```

> data.tf
```terraform
data "template_cloudinit_config" "userdata_linux" {
  count         = var.num_instances
  gzip          = false
  base64_encode = true

  part {
    content_type = "text/cloud-config"
    content      = local.userdata[count.index]
  }
}
```

> resources.tf
```terraform
  extra_config = {
    "guestinfo.userdata"          = data.template_cloudinit_config.userdata_linux[count.index].rendered
    "guestinfo.metadata.encoding" = "base64"
  }
```
